Add encoding parameter
Parquery/reconnecting-ftp pull request #5
Opened 2021-10-07 13:53 UTC by Its-Alex

I need to set encoding using this library, is it possible to add this option ?

2021-10-07 16:15 UTC, mristin commented on reconnecting_ftp/__init__.py
> +                 encoding: str = 'utf-8',
Could you please move the encoding to the end of the argument list to avoid breaking the existing interface?

2021-10-07 16:15 UTC, mristin requested changes
Thanks a lot! Please see a minor comment.

2021-10-10 20:42 UTC, Its-Alex commented on reconnecting_ftp/__init__.py
> +                 encoding: str = 'utf-8',
@mristin Sure! It's done 🙂

2021-10-11 06:54 UTC, merged

2021-10-11 07:05 UTC, mristin commented
@Its-Alex thanks again! The new version should be on PyPI now.

P.S. if you haven't done already, please star the project on GitHub to give it some visibility.